# LiveSpec traceability anchors
# @spec(AC-001)
# @spec(AC-002)
# @spec(AC-003)
# @spec(AC-004)
# @spec(AC-005)
# @spec(AC-006)
# @spec(AC-007)
# @spec(AC-008)
# @spec(AC-009)
# @spec(AC-011)
# @spec(AC-012)
# @spec(AC-013)
# @spec(AC-014)
# @spec(AC-017)

"""Tests for deterministic command goal contracts.

# @spec FR-001, FR-002, FR-003, FR-004, FR-005, FR-006, FR-007, FR-013, FR-014, FR-015, FR-019
#   — .specs/features/052-deterministic-command-goal-contracts/spec.md
"""

# Explicit reexports preserve pytest node IDs and public fixture imports.
from tests._goal_contracts_01 import (
    EXECUTION_TASK_SKILL,
    EXPECTATIONS,
    INLINE_INTERNAL_COMMAND_SKILL,
    SKILL,
    SUBAGENT_INTERNAL_COMMAND_SKILL,
    _fixture_roots,
    _png_chunk,
    _repo_root,
    _write_execution_task_skill,
    _write_internal_command_skill,
    _write_png,
    _write_visual_feature,
)
from tests._goal_contracts_02 import (
    _command_definition_of_done,
    _write_complete_check_fix_scenario,
    _write_conventions,
    _write_conventions_gates,
    _write_fail_conventions_receipt,
    test_compile_command_goal_adds_design_domain_for_ui_feature,
    test_compile_command_goal_embeds_code_convention_domains,
    test_compile_command_goal_is_reproducible_for_same_inputs,
    test_normalize_goal_flags_is_order_independent_and_preserves_values,
)
from tests._goal_contracts_03 import (
    test_compile_command_goal_embeds_non_empty_before_hook_context,
    test_goal_prove_rejects_generic_qe_analysis_evidence,
    test_goal_prove_rejects_qe_analysis_substitutes,
    test_goal_prove_requires_resolved_before_hook_context,
    test_native_qe_analysis_task_is_injected_for_quality_commands,
    test_native_qe_analysis_task_is_not_injected_for_unaffected_commands,
    test_non_init_proof_preserves_missing_task_field_key_error,
    test_non_init_proof_preserves_unknown_task_for_malformed_contract_tasks,
    test_non_init_proof_rejects_present_malformed_state_shapes,
    test_spec_plan_goal_embeds_native_qe_without_user_config,
)
from tests._goal_contracts_04 import (
    test_conventions_gate_not_required_for_spec_feature_supervisor_tasks,
    test_conventions_gate_not_required_for_spec_plan,
    test_conventions_gate_not_required_for_unlisted_command,
    test_conventions_gate_required_for_spec_implement,
    test_goal_prove_accepts_matching_convention_evidence,
    test_goal_prove_accepts_structured_qe_analysis_evidence,
    test_goal_prove_rejects_conventions_receipt_outside_project,
    test_goal_prove_rejects_missing_convention_evidence,
    test_goal_prove_rejects_non_pass_conventions_receipt,
    test_native_qe_is_primary_and_user_hooks_are_additive,
    test_rendered_goal_tasks_replay_required_conventions,
)
from tests._goal_contracts_05 import (
    test_compile_command_goal_accepts_documented_execution_task_branches,
    test_compile_command_goal_activates_spec_check_flag_branches,
    test_compile_command_goal_extracts_definition_of_done,
    test_compile_command_goal_ignores_documentary_and_self_spec_invocations,
    test_compile_command_goal_ignores_markdown_checkboxes_inside_execution_tasks,
    test_compile_command_goal_rejects_any_unknown_internal_invocation_mode,
    test_compile_command_goal_rejects_cli_api_fallback_for_non_spec_command,
    test_compile_command_goal_rejects_executable_spec_invocation_without_section,
    test_compile_command_goal_rejects_inline_internal_spec_invocation,
    test_compile_command_goal_rejects_subagent_non_spec_fallback,
    test_compile_command_goal_rejects_subagent_without_project_root_cwd_guard,
    test_goal_prove_rejects_generic_output_when_required_evidence_missing,
    test_goal_render_save_writes_contract_and_state_files,
    test_render_goal_contract_and_state_replace_markdown_task_file,
)
from tests._goal_contracts_06 import (
    test_compile_command_goal_accepts_subagent_internal_spec_invocation,
    test_compile_command_goal_accepts_updated_real_skills,
    test_compile_command_goal_activates_spec_check_fix_branch,
    test_compile_command_goal_activates_visual_tasks_for_spec_check_all,
    test_compile_command_goal_ignores_horizontal_rule_in_internal_invocations,
    test_compile_command_goal_preserves_existing_execution_task_branches,
    test_compile_command_goal_rejects_malformed_internal_invocation_bullets,
    test_compile_command_goal_respects_explicit_visual_false_marker,
    test_pre_impl_execution_task_branch_active_iff_flag_present,
    test_spec_feature_execution_tasks_include_clarify_gate_before_plan,
)
from tests._goal_contracts_07 import (
    test_child_goal_contract_and_state_paths_may_use_goal_artifacts_outside_project,
    test_child_goal_contract_rejects_arbitrary_absolute_path,
    test_child_goal_contract_rejects_nested_goal_artifact_path,
    test_spec_check_design_fidelity_contract_rejects_normalized_json_substitute,
    test_spec_check_fix_all_complete_scenario_goal_requires_child_goals,
    test_spec_fix_child_spec_check_goal_cannot_be_skipped_with_zero_gap_report,
    test_spec_fix_child_spec_check_skip_requires_zero_gap_report,
)
from tests._goal_contracts_08 import (
    FINALIZE_SKILL,
    _finalize_contract_and_state,
    _finalize_fixture,
    test_anti_drift_block_documents_shared_goal_protocol,
    test_finalize_registry_task_requires_receipt_path,
    test_goal_prove_accepts_visual_design_fidelity_receipt,
    test_goal_prove_rejects_exit_code_and_file_list_substitutes,
    test_goal_prove_rejects_legacy_visual_design_fidelity_payload,
    test_goal_prove_rejects_missing_visual_design_fidelity_evidence,
    test_goal_prove_rejects_prose_finalization_claim,
    test_goal_prove_rejects_visual_receipt_from_wrong_feature,
    test_render_goal_objective_is_stable_text_from_payload,
    test_spec_check_dod_requires_tree_validation_report_not_pass,
)
from tests._goal_contracts_09 import (
    _archive_fixture_artifact,
    _demo_contract_and_state,
    test_archive_run_injection_preserves_hash_determinism,
    test_archive_run_prove_rejects_exit_code_substitute,
    test_archive_run_prove_rejects_path_outside_specs_runs,
    test_archive_run_prove_rejects_prose_claim,
    test_archive_run_prove_rejects_tmpdir_contract_state_paths,
    test_archive_run_task_evidence_family_matches_constants,
    test_archive_run_task_has_strictly_highest_ordinal,
    test_archive_run_task_skips_convention_evidence_layering,
    test_every_contract_carries_exactly_one_archive_run_task,
    test_goal_prove_accepts_valid_finalize_receipt,
    test_goal_prove_rejects_fail_verdict_finalize_receipt,
    test_goal_prove_rejects_tampered_finalize_receipt,
    test_six_registry_commands_carry_finalize_registry_task,
)
from tests._goal_contracts_10 import (
    test_archive_run_end_to_end_drill,
    test_archive_run_prove_accepts_matching_artifact_read_only,
    test_archive_run_prove_accepts_non_latest_matching_artifact,
    test_archive_run_prove_rejects_deleted_artifact_with_repair,
    test_archive_run_prove_rejects_foreign_command_artifact,
    test_archive_run_prove_rejects_foreign_goal_artifact,
    test_archive_run_prove_rejects_malformed_artifact_file,
    test_every_registry_command_contract_ends_with_archive_run,
)

__all__ = [
    "EXECUTION_TASK_SKILL",
    "EXPECTATIONS",
    "FINALIZE_SKILL",
    "INLINE_INTERNAL_COMMAND_SKILL",
    "SKILL",
    "SUBAGENT_INTERNAL_COMMAND_SKILL",
    "_archive_fixture_artifact",
    "_command_definition_of_done",
    "_demo_contract_and_state",
    "_finalize_contract_and_state",
    "_finalize_fixture",
    "_fixture_roots",
    "_png_chunk",
    "_repo_root",
    "_write_complete_check_fix_scenario",
    "_write_conventions",
    "_write_conventions_gates",
    "_write_execution_task_skill",
    "_write_fail_conventions_receipt",
    "_write_internal_command_skill",
    "_write_png",
    "_write_visual_feature",
    "test_anti_drift_block_documents_shared_goal_protocol",
    "test_archive_run_end_to_end_drill",
    "test_archive_run_injection_preserves_hash_determinism",
    "test_archive_run_prove_accepts_matching_artifact_read_only",
    "test_archive_run_prove_accepts_non_latest_matching_artifact",
    "test_archive_run_prove_rejects_deleted_artifact_with_repair",
    "test_archive_run_prove_rejects_exit_code_substitute",
    "test_archive_run_prove_rejects_foreign_command_artifact",
    "test_archive_run_prove_rejects_foreign_goal_artifact",
    "test_archive_run_prove_rejects_malformed_artifact_file",
    "test_archive_run_prove_rejects_path_outside_specs_runs",
    "test_archive_run_prove_rejects_prose_claim",
    "test_archive_run_prove_rejects_tmpdir_contract_state_paths",
    "test_archive_run_task_evidence_family_matches_constants",
    "test_archive_run_task_has_strictly_highest_ordinal",
    "test_archive_run_task_skips_convention_evidence_layering",
    "test_child_goal_contract_and_state_paths_may_use_goal_artifacts_outside_project",
    "test_child_goal_contract_rejects_arbitrary_absolute_path",
    "test_child_goal_contract_rejects_nested_goal_artifact_path",
    "test_compile_command_goal_accepts_documented_execution_task_branches",
    "test_compile_command_goal_accepts_subagent_internal_spec_invocation",
    "test_compile_command_goal_accepts_updated_real_skills",
    "test_compile_command_goal_activates_spec_check_fix_branch",
    "test_compile_command_goal_activates_spec_check_flag_branches",
    "test_compile_command_goal_activates_visual_tasks_for_spec_check_all",
    "test_compile_command_goal_adds_design_domain_for_ui_feature",
    "test_compile_command_goal_embeds_code_convention_domains",
    "test_compile_command_goal_embeds_non_empty_before_hook_context",
    "test_compile_command_goal_extracts_definition_of_done",
    "test_compile_command_goal_ignores_documentary_and_self_spec_invocations",
    "test_compile_command_goal_ignores_horizontal_rule_in_internal_invocations",
    "test_compile_command_goal_ignores_markdown_checkboxes_inside_execution_tasks",
    "test_compile_command_goal_is_reproducible_for_same_inputs",
    "test_compile_command_goal_preserves_existing_execution_task_branches",
    "test_compile_command_goal_rejects_any_unknown_internal_invocation_mode",
    "test_compile_command_goal_rejects_cli_api_fallback_for_non_spec_command",
    "test_compile_command_goal_rejects_executable_spec_invocation_without_section",
    "test_compile_command_goal_rejects_inline_internal_spec_invocation",
    "test_compile_command_goal_rejects_malformed_internal_invocation_bullets",
    "test_compile_command_goal_rejects_subagent_non_spec_fallback",
    "test_compile_command_goal_rejects_subagent_without_project_root_cwd_guard",
    "test_compile_command_goal_respects_explicit_visual_false_marker",
    "test_conventions_gate_not_required_for_spec_feature_supervisor_tasks",
    "test_conventions_gate_not_required_for_spec_plan",
    "test_conventions_gate_not_required_for_unlisted_command",
    "test_conventions_gate_required_for_spec_implement",
    "test_every_contract_carries_exactly_one_archive_run_task",
    "test_every_registry_command_contract_ends_with_archive_run",
    "test_finalize_registry_task_requires_receipt_path",
    "test_goal_prove_accepts_matching_convention_evidence",
    "test_goal_prove_accepts_structured_qe_analysis_evidence",
    "test_goal_prove_accepts_valid_finalize_receipt",
    "test_goal_prove_accepts_visual_design_fidelity_receipt",
    "test_goal_prove_rejects_conventions_receipt_outside_project",
    "test_goal_prove_rejects_exit_code_and_file_list_substitutes",
    "test_goal_prove_rejects_fail_verdict_finalize_receipt",
    "test_goal_prove_rejects_generic_output_when_required_evidence_missing",
    "test_goal_prove_rejects_generic_qe_analysis_evidence",
    "test_goal_prove_rejects_legacy_visual_design_fidelity_payload",
    "test_goal_prove_rejects_missing_convention_evidence",
    "test_goal_prove_rejects_missing_visual_design_fidelity_evidence",
    "test_goal_prove_rejects_non_pass_conventions_receipt",
    "test_goal_prove_rejects_prose_finalization_claim",
    "test_goal_prove_rejects_qe_analysis_substitutes",
    "test_goal_prove_rejects_tampered_finalize_receipt",
    "test_goal_prove_rejects_visual_receipt_from_wrong_feature",
    "test_goal_prove_requires_resolved_before_hook_context",
    "test_goal_render_save_writes_contract_and_state_files",
    "test_native_qe_analysis_task_is_injected_for_quality_commands",
    "test_native_qe_analysis_task_is_not_injected_for_unaffected_commands",
    "test_native_qe_is_primary_and_user_hooks_are_additive",
    "test_non_init_proof_preserves_missing_task_field_key_error",
    "test_non_init_proof_preserves_unknown_task_for_malformed_contract_tasks",
    "test_non_init_proof_rejects_present_malformed_state_shapes",
    "test_normalize_goal_flags_is_order_independent_and_preserves_values",
    "test_pre_impl_execution_task_branch_active_iff_flag_present",
    "test_render_goal_contract_and_state_replace_markdown_task_file",
    "test_render_goal_objective_is_stable_text_from_payload",
    "test_rendered_goal_tasks_replay_required_conventions",
    "test_six_registry_commands_carry_finalize_registry_task",
    "test_spec_check_design_fidelity_contract_rejects_normalized_json_substitute",
    "test_spec_check_dod_requires_tree_validation_report_not_pass",
    "test_spec_check_fix_all_complete_scenario_goal_requires_child_goals",
    "test_spec_feature_execution_tasks_include_clarify_gate_before_plan",
    "test_spec_fix_child_spec_check_goal_cannot_be_skipped_with_zero_gap_report",
    "test_spec_fix_child_spec_check_skip_requires_zero_gap_report",
    "test_spec_plan_goal_embeds_native_qe_without_user_config",
]
