"""Conventions refresh and scaffold helpers."""

from __future__ import annotations

from pathlib import Path

import yaml  # type: ignore[import-untyped]  # PyYAML is runtime-only typed here.

from ..conventions_gates import ConventionsGatesAny


def render_conventions_index(project_name: str, domains: list[str]) -> str:
    """Render `.conventions/index.md`."""
    lines = [
        f"# Conventions · {project_name}",
        "",
        "> Generated by `livespec conventions refresh`.",
        "",
    ]
    entries = {
        "code": (
            "## code [code, tests, logging, naming, Python, CLI, architecture]",
            "→ $AIRESOURCES/code-conventions/general.md, python.md, javascript.md, "
            "cli.md, stack-commands.md",
        ),
        "design-tokens": (
            "## design-tokens [CSS, colors, spacing, typography, motion, dark mode]",
            "→ $AIRESOURCES/design/tokens/colors.md, spacing.md, typography.md, "
            "motion.md, cross-platform.md",
        ),
        "design-components": (
            "## design-components [button, input, form, toast, modal, nav, list, badge]",
            "→ $AIRESOURCES/design/components/buttons.md, forms.md, navigation.md, "
            "lists.md, modals.md, feedback.md",
        ),
        "design-views": (
            "## design-views [page layout, dashboard, settings, auth, mockup specs]",
            "→ $AIRESOURCES/design/references/app-views.md, app-views-catalog.md, "
            "app-ui.md, mockup-specs.md",
        ),
        "design-quality": (
            "## design-quality [a11y audit, WCAG, keyboard nav, ARIA, visual QA]",
            "→ $AIRESOURCES/design/quality/accessibility.md, ui-rules.md",
        ),
    }
    for domain in domains:
        title, source = entries[domain]
        lines.extend([title, source, ""])
    return "\n".join(lines)


def render_conventions_manifest(domains: list[str], stack_text: str) -> str:
    """Render `.conventions/manifest.yaml`."""
    if is_web_ui_stack(stack_text):
        stack_hint = "web"
    elif "python" in stack_text:
        stack_hint = "python"
    else:
        stack_hint = "generic"
    source_map = {
        "code": ["general.md", "python.md", "javascript.md", "cli.md", "stack-commands.md"],
        "design-tokens": [
            "colors.md",
            "spacing.md",
            "typography.md",
            "motion.md",
            "cross-platform.md",
        ],
        "design-components": [
            "buttons.md",
            "forms.md",
            "navigation.md",
            "lists.md",
            "modals.md",
            "feedback.md",
        ],
        "design-views": ["app-views.md", "app-views-catalog.md", "app-ui.md", "mockup-specs.md"],
        "design-quality": ["accessibility.md", "ui-rules.md"],
    }
    prefixes = {
        "code": "$AIRESOURCES/code-conventions",
        "design-tokens": "$AIRESOURCES/design/tokens",
        "design-components": "$AIRESOURCES/design/components",
        "design-views": "$AIRESOURCES/design/references",
        "design-quality": "$AIRESOURCES/design/quality",
    }
    lines = ["version: 1", f"stack_hint: {stack_hint}", "domains:"]
    for domain in domains:
        lines += [f"  - name: {domain}", "    files:"]
        lines += [f"      - {prefixes[domain]}/{name}" for name in source_map[domain]]
    return "\n".join(lines) + "\n"


def is_web_ui_stack(stack_text: str) -> bool:
    """Return whether stack text describes a web UI stack."""
    markers = ("web", "frontend", "react", "vite", "next", "dashboard", "browser", "typescript")
    return any(marker in stack_text for marker in markers)


def scaffold_linter_configs(
    repo_root: Path,
    gates: ConventionsGatesAny,
    *,
    apply: bool,
    sync_limits: bool,
) -> list[str]:
    """Render language-specific linter configs from gates limits."""
    stack_text = _read_stack_text(repo_root)
    specs: list[tuple[str, str, Path]] = []
    if "python" in stack_text:
        specs.append(("python_ruff.toml.tmpl", "pyproject.toml", repo_root / "pyproject.toml"))
    if any(marker in stack_text for marker in ("typescript", "javascript", "react", "node")):
        specs.append(
            ("typescript_eslint.json.tmpl", ".eslintrc.json", repo_root / ".eslintrc.json")
        )
    changed = [
        _write_template(repo_root, gates, item[0], item[1], item[2], apply, sync_limits)
        for item in specs
    ]
    has_swift = "swift" in stack_text or "swift" in gates.coverage
    if has_swift or (repo_root / ".swiftlint.yml").exists():
        changed += _scaffold_swiftlint(repo_root, gates, apply=apply, sync_limits=sync_limits)
    return [item for item in changed if item]


def _read_stack_text(repo_root: Path) -> str:
    path = repo_root / ".specs" / "stacks" / "_default.md"
    return path.read_text(encoding="utf-8").lower() if path.is_file() else ""


def _write_template(
    repo_root: Path,
    gates: ConventionsGatesAny,
    template_name: str,
    display_name: str,
    output_path: Path,
    apply: bool,
    sync_limits: bool,
) -> str:
    if not apply:
        return f"would update {display_name}"
    if output_path.exists() and not sync_limits:
        return f"skipped existing {display_name}"
    text = (_template_root() / template_name).read_text(encoding="utf-8")
    text = text.replace("{{max_file_lines}}", str(gates.builtin.max_file_lines.limit))
    text = text.replace("{{max_function_lines}}", str(gates.builtin.max_function_lines.limit))
    output_path.write_text(text + ("\n" if not text.endswith("\n") else ""), encoding="utf-8")
    return f"updated {output_path.relative_to(repo_root)}"


def _template_root() -> Path:
    return Path(__file__).resolve().parents[2] / "templates" / "conventions"


def _scaffold_swiftlint(
    repo_root: Path,
    gates: ConventionsGatesAny,
    *,
    apply: bool,
    sync_limits: bool,
) -> list[str]:
    path = repo_root / ".swiftlint.yml"
    payload = _read_swiftlint_payload(path)
    payload["file_length"] = {
        "warning": gates.builtin.max_file_lines.target,
        "error": gates.builtin.max_file_lines.limit,
    }
    payload["function_body_length"] = {
        "warning": gates.builtin.max_function_lines.target,
        "error": gates.builtin.max_function_lines.limit,
    }
    if not apply:
        return [f"would update {path.relative_to(repo_root)}"]
    if not sync_limits and path.exists():
        return [f"skipped existing {path.relative_to(repo_root)}"]
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return [f"updated {path.relative_to(repo_root)}"]


def _read_swiftlint_payload(path: Path) -> dict[str, object]:
    if not path.is_file():
        return {}
    try:
        raw: object = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return {}
    return raw if isinstance(raw, dict) else {}
