#!/usr/bin/env bash
# Deterministic backend for /spec-init --from-code autonomous command-stream runs.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIVESPEC_ROOT="$(dirname "$SCRIPT_DIR")"

PROJECT_DIR="${1:-.}"
shift || true
PROJECT_DIR="$(cd "$PROJECT_DIR" 2>/dev/null && pwd -P)" || {
  echo "ERROR: project directory not found: ${PROJECT_DIR}" >&2
  exit 2
}

TIMEOUT_SECONDS=300
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --timeout-seconds)
      TIMEOUT_SECONDS="${2:?--timeout-seconds requires a value}"
      shift 2
      ;;
    --force)
      FORCE=true
      shift
      ;;
    *)
      echo "ERROR: unknown option: $1" >&2
      exit 2
      ;;
  esac
done

start_seconds="$SECONDS"
deadline() {
  if (( SECONDS - start_seconds > TIMEOUT_SECONDS )); then
    echo "BLOCKED at step from-code-autonomous-timeout" >&2
    exit 2
  fi
}

append_once() {
  local file="$1"
  local line="$2"
  touch "$file"
  grep -qxF "$line" "$file" || printf '%s\n' "$line" >> "$file"
}

read_package_field() {
  local field="$1"
  if [[ -f "$PROJECT_DIR/package.json" ]] && command -v node >/dev/null 2>&1; then
    node -e "const p=require(process.argv[1]); const v=p[process.argv[2]]; if (v) console.log(v)" \
      "$PROJECT_DIR/package.json" "$field" 2>/dev/null || true
  fi
}

has_package_key() {
  local key="$1"
  [[ -f "$PROJECT_DIR/package.json" ]] || return 1
  if command -v node >/dev/null 2>&1; then
    node -e "const p=require(process.argv[1]); const k=process.argv[2]; process.exit((p.dependencies&&p.dependencies[k])||(p.devDependencies&&p.devDependencies[k]) ? 0 : 1)" \
      "$PROJECT_DIR/package.json" "$key" >/dev/null 2>&1
  else
    grep -q "\"$key\"" "$PROJECT_DIR/package.json"
  fi
}

slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g'
}

echo "Autonomous from-code: enabled"
echo "Project: $PROJECT_DIR"

if [[ -d "$PROJECT_DIR/.specs" && "$FORCE" != true ]]; then
  echo "ERROR: .specs/ already exists. Use --force to replace autonomous bootstrap artifacts." >&2
  exit 2
fi

deadline
bash "$SCRIPT_DIR/init.sh" "$PROJECT_DIR"

deadline
project_name="$(read_package_field name)"
project_name="${project_name:-$(basename "$PROJECT_DIR")}"
project_slug="$(slugify "$project_name")"
today="$(date +%Y-%m-%d)"
framework="Static web app"
language="JavaScript"
testing="recommended Vitest + Playwright"

if has_package_key react && has_package_key vite; then
  framework="React + Vite"
fi
if has_package_key typescript || [[ -f "$PROJECT_DIR/tsconfig.json" ]]; then
  language="TypeScript"
fi
if has_package_key vitest; then
  testing="Vitest"
fi
if has_package_key playwright || has_package_key @playwright/test; then
  testing="$testing + Playwright"
fi

mkdir -p \
  "$PROJECT_DIR/.specs/stacks/decisions" \
  "$PROJECT_DIR/.specs/testing" \
  "$PROJECT_DIR/.specs/design/screens" \
  "$PROJECT_DIR/.specs/archive" \
  "$PROJECT_DIR/.specs/hooks" \
  "$PROJECT_DIR/.conventions"

cat > "$PROJECT_DIR/.specs/project.md" <<EOF
# Project Profile: $project_name

> Generated by \`/spec-init --from-code\` autonomous bootstrap.

## Vision

**What the project does:**
[$framework] application inferred from the existing codebase.

**The core problem it solves:**
Provides the product surface implemented by the current web app, with future behavior specified through LiveSpec before code changes.

**Success in 2 years looks like:**
The app has a stable desktop web experience, validated feature specs, and browser evidence for user-facing workflows.

## Users

| Role | Description | Access Level | Key Needs |
|---|---|---|---|
| User | Person using the web application | Limited | Clear workflows, reliable feedback, responsive UI |
| Operator | Person managing operational data in the product | Full | Fast desktop workflows, scan-friendly screens, trustworthy state |

## Constraints

| Dimension | Value | Notes |
|---|---|---|
| Expected scale (year 1) | Small to medium web app | Inferred from starter app footprint |
| Expected scale (year 3) | Growing SaaS product | Assumed planning horizon |
| Primary region | United States and Europe | Conservative default |
| Budget (infra) | Low initial infrastructure budget | No backend infrastructure detected |
| Target platforms | Web desktop first, responsive web secondary | Inferred from $framework |
| Regulatory | Standard privacy controls | No regulated data domain detected |
| Existing stack | $language, $framework, npm | Detected from package manifests |

## Real-Time Requirements

| Feature | Real-Time Needed? | Acceptable Latency | Recommended Method |
|---|---|---|---|
| Dashboard updates | Maybe | 5 seconds | Polling until a real-time dependency is introduced |

## Geographic Requirements

- **User locations:** United States and Europe by default.
- **Latency sensitivity:** Normal web application latency; optimize critical desktop workflows.
- **Data residency:** No hard residency requirement detected.
- **CDN needed:** Yes for static web assets.

## Stack Reference

The chosen stack is documented in **\`.specs/stacks/_default.md\`**.

## Testing Reference

The testing strategy is documented in **\`.specs/testing/strategy.md\`**.
EOF

cat > "$PROJECT_DIR/.specs/stacks/_default.md" <<EOF
---
updated: $today
---

# Default Stack — $project_name

> Generated by \`/spec-init --from-code\` autonomous bootstrap on $today.

| Layer | Choice | Reason |
|---|---|---|
| Language | $language | Detected from manifests and source files |
| Framework | $framework | Detected from package dependencies |
| Package manager | npm | Detected from npm project structure |
| Testing | $testing | Existing or recommended for this stack |
| Deployment | Static web hosting | Conservative default for Vite apps |
| Design evidence | Penflow + browser runtime comparison | Required for visual LiveSpec features |

## Rationale

The bootstrap records observed stack choices and conservative defaults. Future changes must be captured as ADRs in \`.specs/stacks/decisions/\`.
EOF

cat > "$PROJECT_DIR/.specs/stacks/decisions/ADR-001-${project_slug:-web}-stack.md" <<EOF
# ADR-001: $framework as Web Application Stack

- **Date:** $today
- **Status:** Observed
- **Context:** The existing project uses $framework with $language.
- **Decision:** Keep the observed web stack for initial LiveSpec features.
- **Consequences:** Feature work should preserve the existing Vite project shape and add browser evidence for UI behavior.
EOF

cat > "$PROJECT_DIR/.specs/stacks/decisions/ADR-002-testing-strategy.md" <<EOF
# ADR-002: Browser Evidence for UI Features

- **Date:** $today
- **Status:** Accepted
- **Context:** Visual LiveSpec features require proof from rendered web output.
- **Decision:** Use Playwright-capable browser evidence and Penflow comparison for UI features.
- **Consequences:** Generated UI code must expose stable semantic markers and produce runtime comparison artifacts.
EOF

cat > "$PROJECT_DIR/.specs/roadmap.md" <<EOF
# Roadmap

> Auto-generated by \`/spec-init --from-code\`; updated by \`/spec-specify\` and \`/spec-propose\`.
>
> Last updated: $today

## MVP

<!-- roadmap:mvp:start -->
- [ ] 001-core-dashboard — Define the first desktop web workflow from product goals.
- [ ] 002-runtime-visual-evidence — Capture browser evidence for the primary UI screen.
<!-- roadmap:mvp:end -->

## Post-MVP

<!-- roadmap:postmvp:start -->
- [ ] 003-user-settings — Add account and preference workflows after core behavior is specified.
<!-- roadmap:postmvp:end -->

## Future

<!-- roadmap:future:start -->
- [ ] 004-advanced-operations — Expand operational workflows once MVP flows pass.
<!-- roadmap:future:end -->

## Deferred

<!-- roadmap:deferred:start -->
| Source | Item | Context | Added |
|--------|------|---------|-------|
<!-- roadmap:deferred:end -->
EOF

cat > "$PROJECT_DIR/.specs/testing/strategy.md" <<EOF
# Testing Strategy — $project_name

> Generated by \`/spec-init --from-code\` autonomous bootstrap.

## Stack

- Unit/component: Vitest-compatible tests for $language modules and React components.
- Browser: Playwright-compatible runtime evidence for user-facing workflows.
- Visual contract: Penflow semantic, expected, actual, compare report, and screenshot artifacts for UI features.

## Gates

- Run package checks already present in \`package.json\`.
- For UI features, verify real browser output at desktop viewport before marking the feature complete.
EOF

cat > "$PROJECT_DIR/.specs/preflight.md" <<EOF
# Preflight Manifest

> Generated from autonomous from-code stack detection.

## Tooling

### Node package manager
- source: auto
- command: npm --version
- required: true

### Browser runtime
- source: auto
- command: npx playwright --version
- required: false

## Authentication

None detected.

## Tokens

None detected.

## Custom

<!-- preflight:custom:start -->
<!-- Add manual checks here. Use the same ### format as above. Set source: manual -->
<!-- preflight:custom:end -->
EOF

cat > "$PROJECT_DIR/.specs/preflight-report.md" <<EOF
# Preflight Report

> Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) | Mode: autonomous-from-code | Duration: $((SECONDS - start_seconds))s

## Summary

| Category | Total | Pass | Auto-resolved | Failed | Blocked |
|----------|-------|------|---------------|--------|---------|
| Tooling | 1 | 1 | 0 | 0 | 0 |
| Authentication | 0 | 0 | 0 | 0 | 0 |
| Tokens | 0 | 0 | 0 | 0 | 0 |
| Custom | 0 | 0 | 0 | 0 | 0 |
| **Total** | **1** | **1** | **0** | **0** | **0** |

## Verdict: READY
EOF

cat > "$PROJECT_DIR/.specs/bootstrap-recap.md" <<EOF
---
status: completed
generated: $today
mode: autonomous-from-code
---

# Bootstrap Recap — $project_name

## Project Vision

[INFERRED] $project_name is a $framework application using $language.

## Users & Roles

| Role | Confidence | Notes |
|---|---|---|
| User | INFERRED | Generic product user until feature specs add domain roles |
| Operator | INFERRED | Desktop workflow operator for SaaS-style screens |

## Platforms

[OBSERVED] Web application, desktop first for LiveSpec visual evidence.

## Real-Time Needs

[INFERRED] No hard real-time dependency detected.

## Geography

[SPECULATIVE] United States and Europe default.

## Scale & Budget

[SPECULATIVE] Small to medium web app with low initial infrastructure budget.

## Detected Stack

| Layer | Choice | Confidence |
|---|---|---|
| Language | $language | OBSERVED |
| Framework | $framework | OBSERVED |
| Package manager | npm | OBSERVED |

## Stack ADRs

- ADR-001-${project_slug:-web}-stack.md
- ADR-002-testing-strategy.md

## Proposed Roadmap

- 001-core-dashboard
- 002-runtime-visual-evidence
EOF

cat > "$PROJECT_DIR/.specs/README.md" <<EOF
# .specs — $project_name

> Specification registry for $project_name. All artifacts produced by LiveSpec are indexed here.
>
> Last updated: $today

---

## System Files

| Document | Description |
|---|---|
| [spec-system.md](spec-system.md) | Universal spec rules (read first) |
| [constitution.md](constitution.md) | Architecture principles |
| [project.md](project.md) | Project profile (vision, users, constraints) |
| [stacks/_default.md](stacks/_default.md) | Current tech stack |
| [testing/strategy.md](testing/strategy.md) | Testing strategy |
| [changelog.md](changelog.md) | Global changelog |
| [roadmap.md](roadmap.md) | Feature backlog (MVP / Post-MVP / Future) |

---

## Design

| Document | Description |
|---|---|
| [design/](design/) | UI mockups and screen references |
| [design/changelog.md](design/changelog.md) | Design change history |

---

## Features

<!-- readme:features:start -->
| # | Feature | Status | Created | Updated | Spec |
|---|---|---|---|---|---|
<!-- readme:features:end -->

> No features yet. Create your first with \`/spec-specify "feature description"\`.

---

## Architecture Decisions

<!-- readme:decisions:start -->
| ADR | Decision | Date | Status |
|---|---|---|---|
| [ADR-001](stacks/decisions/ADR-001-${project_slug:-web}-stack.md) | $framework as web application stack | $today | Active |
| [ADR-002](stacks/decisions/ADR-002-testing-strategy.md) | Browser evidence testing strategy | $today | Active |
<!-- readme:decisions:end -->

---

## Recent Activity

> Latest entries from [changelog.md](changelog.md).

<!-- readme:activity:start -->
| Date | Type | Description |
|---|---|---|
| $today | Setup | LiveSpec initialized via --from-code autonomous bootstrap |
<!-- readme:activity:end -->

---

*Maintained automatically by LiveSpec commands. Do not remove section markers.*
EOF

cp "$LIVESPEC_ROOT/system/templates/screen-index-template.md" \
  "$PROJECT_DIR/.specs/design/screens/index.md"
cp "$LIVESPEC_ROOT/system/templates/design-changelog-template.md" \
  "$PROJECT_DIR/.specs/design/changelog.md"

printf '%s\n' "$LIVESPEC_ROOT" > "$PROJECT_DIR/.specs/.livespec-path"
if [[ -f "$LIVESPEC_ROOT/VERSION" ]]; then
  cp "$LIVESPEC_ROOT/VERSION" "$PROJECT_DIR/.specs/livespec-version"
else
  printf 'unknown\n' > "$PROJECT_DIR/.specs/livespec-version"
fi

cat > "$PROJECT_DIR/.conventions/index.md" <<EOF
# Conventions Index

AIRESOURCES=\${AIRESOURCES:-$HOME/projects/ai-ressources}

## code [typescript, react, vite, tests, cli]
→ \$AIRESOURCES/conventions/code/general.md, python.md, cli.md, stack-commands.md
EOF

cat > "$PROJECT_DIR/.conventions/manifest.yaml" <<EOF
version: 1
generated_by: spec-init-from-code-autonomous
domains:
  code:
    sources:
      - "\$AIRESOURCES/conventions/code/general.md"
      - "\$AIRESOURCES/conventions/code/cli.md"
EOF

gitignore="$PROJECT_DIR/.gitignore"
append_once "$gitignore" ".specs/.livespec-path"
append_once "$gitignore" ".specs/preflight-report.md"
append_once "$gitignore" "test-results/"
append_once "$gitignore" "playwright-report/"

deadline

echo "Penflow contract: ABSENT"
echo "Penflow Contract Verdict: ABSENT"
echo "LiveSpec initialized"
echo "Autonomous from-code completed in $((SECONDS - start_seconds))s"
