#!/usr/bin/env bash
# LiveSpec traceability anchors
# @spec(FR-040)

set -euo pipefail

# Migration v20 wrapper: force all v2 journey manifests and native artifacts to
# be regenerated by the LiveSpec version being applied, not by a possibly stale
# globally installed CLI.

PROJECT_DIR="${1:?Usage: migrate-journeys-compile.sh <project-dir> <livespec-dir>}"
LIVESPEC_DIR="${2:?Usage: migrate-journeys-compile.sh <project-dir> <livespec-dir>}"

cd "$PROJECT_DIR"
PYTHONPATH="$LIVESPEC_DIR${PYTHONPATH:+:$PYTHONPATH}" python3 -m validator.cli journey compile --force
