"""Scaffold a custom driver YAML for an unsupported stack."""

# @spec FR-006: The CLI can scaffold a project-local driver manifest from a template.
# @spec AC-008: The scaffold includes detect rules and every executable capability section.


from __future__ import annotations

from pathlib import Path

TEMPLATE = """# LiveSpec test driver — {stack}
# Generated by `livespec spec-driver --new {stack}`.
# See .specs/spec-system.md for integration details.

name: {stack}

# detect: file globs (top-level only) used to identify the stack.
detect:
  files: []

# coverage capability — produces an lcov.info report.
# coverage:
#   command: "<runner that produces lcov.info>"
#   report_path: coverage/lcov.info
#   threshold: 0.85
#   patch_threshold: 0.80

# snapshots capability — golden-file / snapshot tests.
# snapshots:
#   command: "<snapshot test runner>"

# properties capability — property-based / fuzz testing.
# properties:
#   command: "<property test runner>"

# mutation capability — mutation testing.
# mutation:
#   command: "<mutation test runner>"
#   report_path: mutation-report.json
"""


class DriverFileExistsError(FileExistsError):
    """Raised when the scaffold target already exists and ``--force`` is absent."""


def scaffold_custom_driver(
    stack: str,
    *,
    project_root: Path | None = None,
    force: bool = False,
) -> Path:
    """Write ``.specs/drivers/<stack>.yaml`` from the template.

    Args:
        stack: Stack slug to embed in the scaffolded filename and manifest.
        project_root: Repository root where the custom driver directory lives.
        force: Whether to overwrite an existing manifest file.

    Returns:
        Path to the scaffolded manifest file.

    Raises:
        ValueError: ``stack`` is empty or would escape the target directory.
        DriverFileExistsError: The target file exists and ``force`` is ``False``.
    """
    if not stack or "/" in stack or stack.startswith("."):
        raise ValueError(f"Invalid stack name: {stack!r}")
    root = project_root or Path.cwd()
    target_dir = root / ".specs" / "drivers"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{stack}.yaml"
    if target.exists() and not force:
        raise DriverFileExistsError(
            f"Driver {target} already exists. Use --force to overwrite."
        )
    target.write_text(TEMPLATE.format(stack=stack), encoding="utf-8")
    return target
