"""Scaffold a custom driver YAML for an unsupported stack."""

# @spec FR-006: livespec spec-driver --new <stack> — .specs/features/016-cross-language-test-driver-architecture/spec.md#fr-006  # noqa: E501
# @spec AC-008: Scaffold all 5 capability sections + --force — .specs/features/016-cross-language-test-driver-architecture/spec.md#ac-008  # noqa: E501


from __future__ import annotations

from pathlib import Path

TEMPLATE = """# LiveSpec test driver — {stack}
# Generated by `livespec spec-driver --new {stack}`.
# See .specs/spec-system.md for integration details.

name: {stack}

# detect: file globs (top-level only) used to identify the stack.
detect:
  files: []

# coverage capability — produces an lcov.info report.
# coverage:
#   command: "<runner that produces lcov.info>"
#   report_path: coverage/lcov.info
#   threshold: 0.85
#   patch_threshold: 0.80

# snapshots capability — golden-file / snapshot tests.
# snapshots:
#   command: "<snapshot test runner>"

# properties capability — property-based / fuzz testing.
# properties:
#   command: "<property test runner>"

# mutation capability — mutation testing.
# mutation:
#   command: "<mutation test runner>"
#   report_path: mutation-report.json
"""


class DriverFileExistsError(FileExistsError):
    """Raised when the scaffold target already exists and --force is absent."""


def scaffold_custom_driver(
    stack: str,
    *,
    project_root: Path | None = None,
    force: bool = False,
) -> Path:
    """Write `.specs/drivers/<stack>.yaml` from the template. Return the file path."""
    if not stack or "/" in stack or stack.startswith("."):
        raise ValueError(f"Invalid stack name: {stack!r}")
    root = project_root or Path.cwd()
    target_dir = root / ".specs" / "drivers"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{stack}.yaml"
    if target.exists() and not force:
        raise DriverFileExistsError(
            f"Driver {target} already exists. Use --force to overwrite."
        )
    target.write_text(TEMPLATE.format(stack=stack), encoding="utf-8")
    return target
