"""Generate per-stack test config files from a detected DriverManifest.

Feature 026: conventions propagation by stack. Given the primary driver detected
for a project, produce the files that wire the test runner's coverage gate plus
a CI workflow that calls ``livespec spec.test``. The conventions index is also
updated with a ``testing`` domain entry so downstream AI tools know what is
configured.
"""

# @spec FR-001: generate_test_config returns list[GeneratedFile] per stack.
# @spec FR-002: Per-stack config generators (python/typescript/swift/go/rust/jvm).
# @spec FR-003: generate_ci_workflow returns YAML calling livespec spec.test.
# @spec FR-004: update_conventions_testing_domain patches .conventions/index.md.
# @spec AC-001: Detected supported stack -> coverage config in runner config file.
# @spec AC-002: Unsupported stack -> note + skip without blocking.
# @spec AC-003: Generated CI calls `livespec spec.test`, includes install step.
# @spec AC-004: Default coverage threshold 70 (configurable).
# @spec AC-005: testing entry added/updated in .conventions/index.md.
# @spec AC-006: Conventions update reused by spec.refresh-conventions.
# @spec AC-007: Caller can list generated files in completion summary.
# @spec AC-008: Generated config does not break existing project files.
# @spec EC-001: vitest.config.ts existing -> patch coverage section, no overwrite.
# @spec EC-002: .github/workflows/test.yml existing -> skip, do not overwrite.
# @spec EC-003: Polyglot project -> primary driver = most matched files.
# @spec EC-004: Missing .github/ directory created when writing the workflow.

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from .schemas import DriverManifest

WriteMode = Literal["create", "patch_section", "skip_if_exists"]

DEFAULT_THRESHOLD = 70.0


@dataclass(frozen=True)
class GeneratedFile:
    """A file to materialize during ``/spec.init`` or ``livespec init test-config``.

    Attributes:
        path: Project-root-relative path of the file to write.
        content: File contents (or section body when ``mode == 'patch_section'``).
        mode: Write strategy. ``create`` always writes; ``skip_if_exists`` skips
            when the file already exists; ``patch_section`` inserts/replaces the
            block delimited by LiveSpec markers when the file already exists.
        section_marker: Stable identifier injected as ``# livespec:testing:<marker>``
            anchors when patching. Required for ``patch_section`` files.
    """

    path: Path
    content: str
    mode: WriteMode = "create"
    section_marker: str | None = None


# ---------------------------------------------------------------------------
# CI workflow
# ---------------------------------------------------------------------------


CI_WORKFLOW_PATH = Path(".github/workflows/test.yml")


def generate_ci_workflow(driver: DriverManifest) -> GeneratedFile:
    """Render a GitHub Actions workflow that runs ``livespec spec.test``.

    Args:
        driver: Detected primary driver. Currently used only to decide which
            language toolchain step to add before LiveSpec is installed.

    Returns:
        A ``GeneratedFile`` for ``.github/workflows/test.yml`` with
        ``mode='skip_if_exists'`` so existing CI is never overwritten.
    """
    setup_step = _ci_setup_step(driver.name)
    content = (
        "# Generated by LiveSpec (feature 026). Calls `livespec spec.test`\n"
        "# so the test driver orchestration is exercised in CI.\n"
        "name: tests\n"
        "on:\n"
        "  push:\n"
        "  pull_request:\n"
        "jobs:\n"
        "  test:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        f"{setup_step}"
        "      - name: Install LiveSpec\n"
        "        run: pip install livespec-validator\n"
        "      - name: Run LiveSpec test orchestration\n"
        "        run: livespec spec.test\n"
    )
    return GeneratedFile(path=CI_WORKFLOW_PATH, content=content, mode="skip_if_exists")


def _ci_setup_step(driver_name: str) -> str:
    """Return the language-specific setup step inserted before LiveSpec install.

    Args:
        driver_name: Driver manifest name. Unknown drivers fall back to a Python
            setup step (LiveSpec itself is a Python package).

    Returns:
        YAML fragment (already indented with six spaces) ending with a newline.
    """
    if driver_name == "typescript":
        return (
            "      - uses: actions/setup-node@v4\n"
            "        with:\n"
            "          node-version: '20'\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
        )
    if driver_name == "go":
        return (
            "      - uses: actions/setup-go@v5\n"
            "        with:\n"
            "          go-version: '1.22'\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
        )
    if driver_name == "rust":
        return (
            "      - uses: dtolnay/rust-toolchain@stable\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
        )
    if driver_name == "jvm":
        return (
            "      - uses: actions/setup-java@v4\n"
            "        with:\n"
            "          distribution: temurin\n"
            "          java-version: '21'\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
        )
    if driver_name == "swift":
        return (
            "      - uses: swift-actions/setup-swift@v2\n"
            "      - uses: actions/setup-python@v5\n"
            "        with:\n"
            "          python-version: '3.11'\n"
        )
    # Python and unknown drivers — Python is enough since LiveSpec runs on it.
    return (
        "      - uses: actions/setup-python@v5\n"
        "        with:\n"
        "          python-version: '3.11'\n"
    )


# ---------------------------------------------------------------------------
# Per-stack coverage config generators
# ---------------------------------------------------------------------------


def python_config(threshold: float) -> GeneratedFile:
    """Return the ``pyproject.toml`` patch enabling coverage gating.

    Args:
        threshold: Minimum coverage percentage to enforce.

    Returns:
        A ``GeneratedFile`` patching the ``[tool.coverage.report]`` table.
    """
    body = (
        "[tool.coverage.report]\n"
        f"fail_under = {threshold:g}\n"
        "show_missing = true\n"
    )
    return GeneratedFile(
        path=Path("pyproject.toml"),
        content=body,
        mode="patch_section",
        section_marker="python-coverage",
    )


def typescript_config(threshold: float) -> GeneratedFile:
    """Return the ``vitest.config.ts`` patch enabling coverage thresholds.

    Args:
        threshold: Minimum coverage percentage to enforce on lines.

    Returns:
        A ``GeneratedFile`` patching the vitest coverage section. The patch is
        valid TypeScript so the snippet can be inlined with `// livespec` markers.
    """
    body = (
        "// LiveSpec-managed vitest coverage thresholds.\n"
        "export const livespecCoverage = {\n"
        "  provider: 'v8',\n"
        "  reporter: ['text', 'lcov'],\n"
        "  thresholds: {\n"
        f"    lines: {threshold:g},\n"
        f"    statements: {threshold:g},\n"
        f"    functions: {threshold:g},\n"
        f"    branches: {threshold:g},\n"
        "  },\n"
        "};\n"
    )
    return GeneratedFile(
        path=Path("vitest.config.ts"),
        content=body,
        mode="patch_section",
        section_marker="typescript-coverage",
    )


def swift_config(threshold: float) -> GeneratedFile:
    """Return a Swift coverage config snippet (XCTest + xccov)."""
    body = (
        "# LiveSpec-managed Swift coverage gate (feature 026).\n"
        "# Run `swift test --enable-code-coverage` then check this threshold via xccov.\n"
        f"threshold: {threshold:g}\n"
        "report: build/coverage.xcresult\n"
    )
    return GeneratedFile(
        path=Path(".swift-coverage.yml"),
        content=body,
        mode="skip_if_exists",
    )


def go_config(threshold: float) -> GeneratedFile:
    """Return a Go coverage config snippet."""
    body = (
        "# LiveSpec-managed Go coverage gate (feature 026).\n"
        "# Use with `go test -coverprofile=coverage.out ./...`.\n"
        f"threshold: {threshold:g}\n"
        "profile: coverage.out\n"
    )
    return GeneratedFile(
        path=Path(".go-coverage.yml"),
        content=body,
        mode="skip_if_exists",
    )


def rust_config(threshold: float) -> GeneratedFile:
    """Return a Rust coverage config snippet (cargo-tarpaulin)."""
    body = (
        "# LiveSpec-managed cargo-tarpaulin config (feature 026).\n"
        "[report]\n"
        "out = [\"Lcov\"]\n"
        "[run]\n"
        f"fail-under = {threshold:g}\n"
    )
    return GeneratedFile(
        path=Path("tarpaulin.toml"),
        content=body,
        mode="skip_if_exists",
    )


def jvm_config(threshold: float) -> GeneratedFile:
    """Return a JaCoCo coverage config snippet."""
    body = (
        "// LiveSpec-managed JaCoCo coverage gate (feature 026).\n"
        "// Apply via build.gradle(.kts): `apply from: 'jacoco-livespec.gradle'`.\n"
        "jacocoTestCoverageVerification {\n"
        "    violationRules {\n"
        "        rule {\n"
        "            limit {\n"
        f"                minimum = {threshold / 100:.2f}\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "}\n"
    )
    return GeneratedFile(
        path=Path("jacoco-livespec.gradle"),
        content=body,
        mode="skip_if_exists",
    )


_GENERATORS: dict[str, Callable[[float], GeneratedFile]] = {
    "python": python_config,
    "typescript": typescript_config,
    "swift": swift_config,
    "go": go_config,
    "rust": rust_config,
    "jvm": jvm_config,
}


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------


@dataclass
class TestConfigPlan:
    """Result of ``generate_test_config`` ready to be written to disk.

    Attributes:
        files: Ordered list of files to create or patch.
        runner: Stack-specific test runner name (e.g. ``pytest``, ``vitest``).
        snapshot_lib: Snapshot library if known, otherwise ``"none"``.
        threshold: Configured coverage threshold (percentage 0-100).
    """

    files: list[GeneratedFile] = field(default_factory=list[GeneratedFile])
    runner: str = ""
    snapshot_lib: str = "none"
    threshold: float = DEFAULT_THRESHOLD


def generate_test_config(
    driver: DriverManifest,
    project_root: Path,
    threshold: float = DEFAULT_THRESHOLD,
) -> TestConfigPlan:
    """Build the full test config plan for a project's primary driver.

    Args:
        driver: The detected primary ``DriverManifest``.
        project_root: Repository root (kept for future driver-specific decisions
            such as detecting `pnpm-workspace.yaml` polyglots).
        threshold: Coverage percentage to enforce. Defaults to
            :data:`DEFAULT_THRESHOLD`.

    Returns:
        A :class:`TestConfigPlan` with the coverage config + CI workflow files
        and metadata used to update the conventions ``testing`` domain.

    Raises:
        ValueError: If ``threshold`` is outside the (0, 100] range.
    """
    if not 0.0 < threshold <= 100.0:
        raise ValueError(f"threshold must be in (0, 100], got {threshold}")
    # project_root is reserved for future polyglot heuristics; reference it so
    # static checkers do not flag it as unused while keeping the public API
    # forward-compatible (EC-003 will refine the primary-driver pick here).
    _ = project_root
    plan = TestConfigPlan(threshold=threshold)
    generator = _GENERATORS.get(driver.name)
    if generator is not None:
        plan.files.append(generator(threshold))
    plan.files.append(generate_ci_workflow(driver))
    plan.runner = _runner_for(driver)
    plan.snapshot_lib = _snapshot_lib_for(driver)
    return plan


def _runner_for(driver: DriverManifest) -> str:
    """Infer the user-facing test runner name from a driver manifest."""
    coverage = driver.coverage
    command = (coverage.command or coverage.script or "") if coverage else ""
    lowered = command.lower()
    if "pytest" in lowered:
        return "pytest"
    if "vitest" in lowered:
        return "vitest"
    if "jest" in lowered:
        return "jest"
    if "swift test" in lowered:
        return "swift test"
    if "go test" in lowered:
        return "go test"
    if "cargo" in lowered or "tarpaulin" in lowered:
        return "cargo test"
    if "gradle" in lowered:
        return "gradle test"
    if "mvn" in lowered:
        return "mvn test"
    return driver.name


def _snapshot_lib_for(driver: DriverManifest) -> str:
    """Infer a snapshot library label from the driver's snapshot capability."""
    snapshots = driver.snapshots
    if snapshots is None:
        return "none"
    command = (snapshots.command or snapshots.script or "").lower()
    if "syrupy" in command or "pytest" in command:
        return "syrupy"
    if "vitest" in command or "jest" in command:
        return "vitest snapshot"
    if "swift" in command:
        return "swift-snapshot-testing"
    return "custom"


# ---------------------------------------------------------------------------
# Conventions index update
# ---------------------------------------------------------------------------


_CONV_BEGIN = "<!-- livespec:testing:begin -->"
_CONV_END = "<!-- livespec:testing:end -->"


def update_conventions_testing_domain(
    plan: TestConfigPlan,
    driver: DriverManifest,
    conventions_index: Path,
) -> bool:
    """Insert or replace the ``testing`` domain block in ``.conventions/index.md``.

    Args:
        plan: The plan returned by :func:`generate_test_config`.
        driver: The driver used for that plan (used for the ``Stack`` label).
        conventions_index: Absolute path to ``.conventions/index.md``.

    Returns:
        ``True`` if the file was created or rewritten, ``False`` if the
        conventions index does not exist (graceful no-op).
    """
    if not conventions_index.is_file():
        return False
    block = _render_conventions_block(plan, driver)
    original = conventions_index.read_text(encoding="utf-8")
    if _CONV_BEGIN in original and _CONV_END in original:
        before, _, rest = original.partition(_CONV_BEGIN)
        _, _, after = rest.partition(_CONV_END)
        new_text = f"{before.rstrip()}\n\n{block}\n{after.lstrip()}"
    else:
        suffix = "" if original.endswith("\n") else "\n"
        new_text = f"{original}{suffix}\n{block}\n"
    conventions_index.write_text(new_text, encoding="utf-8")
    return True


def _render_conventions_block(plan: TestConfigPlan, driver: DriverManifest) -> str:
    """Render the conventions ``testing`` domain block for the index file."""
    coverage_files = ", ".join(
        str(f.path) for f in plan.files if f.path != CI_WORKFLOW_PATH
    ) or "(none)"
    return (
        f"{_CONV_BEGIN}\n"
        "## testing [test, coverage, snapshot, ci]\n"
        f"- Stack: {driver.name}\n"
        f"- Runner: {plan.runner}\n"
        f"- Coverage threshold: {plan.threshold:g}%\n"
        f"- Snapshot library: {plan.snapshot_lib}\n"
        f"- Coverage config: {coverage_files}\n"
        f"- CI workflow: {CI_WORKFLOW_PATH}\n"
        "- Run locally: `livespec spec.test`\n"
        f"{_CONV_END}"
    )


# ---------------------------------------------------------------------------
# File materialization
# ---------------------------------------------------------------------------


@dataclass
class WriteOutcome:
    """Outcome of materializing a single ``GeneratedFile``.

    Attributes:
        path: Project-root-relative path that was processed.
        action: ``"created"``, ``"patched"``, or ``"skipped"``.
        reason: Optional reason — e.g. ``"file exists"`` for skipped writes.
    """

    path: Path
    action: Literal["created", "patched", "skipped"]
    reason: str = ""


def materialize_files(
    files: list[GeneratedFile],
    project_root: Path,
    *,
    force: bool = False,
) -> list[WriteOutcome]:
    """Write the planned files to disk honoring each entry's mode.

    Args:
        files: ``GeneratedFile`` entries returned by :func:`generate_test_config`.
        project_root: Repository root used as the base for relative paths.
        force: When ``True``, ``skip_if_exists`` files are still overwritten.
            ``patch_section`` files are always patched in place; this flag does
            not change their behavior.

    Returns:
        One :class:`WriteOutcome` per entry, in the same order as ``files``.
    """
    outcomes: list[WriteOutcome] = []
    for entry in files:
        target = project_root / entry.path
        target.parent.mkdir(parents=True, exist_ok=True)
        if entry.mode == "create":
            target.write_text(entry.content, encoding="utf-8")
            outcomes.append(WriteOutcome(entry.path, "created"))
            continue
        if entry.mode == "skip_if_exists":
            if target.exists() and not force:
                outcomes.append(
                    WriteOutcome(entry.path, "skipped", "file exists"),
                )
                continue
            target.write_text(entry.content, encoding="utf-8")
            outcomes.append(WriteOutcome(entry.path, "created"))
            continue
        # patch_section
        marker = entry.section_marker or entry.path.name
        outcomes.append(_patch_section(target, entry.content, marker, entry.path))
    return outcomes


def _patch_section(
    target: Path,
    body: str,
    marker: str,
    rel_path: Path,
) -> WriteOutcome:
    """Insert/replace a ``# livespec:testing:<marker>`` block in ``target``.

    Args:
        target: Absolute path of the file to patch.
        body: Content placed between the begin/end markers.
        marker: Stable identifier so multiple LiveSpec blocks can coexist.
        rel_path: Project-root-relative path used in the returned outcome.

    Returns:
        A :class:`WriteOutcome` describing whether the file was created (no
        prior content) or patched in place.
    """
    begin = f"# livespec:testing:{marker}:begin"
    end = f"# livespec:testing:{marker}:end"
    block = f"{begin}\n{body.rstrip()}\n{end}\n"
    if not target.exists():
        target.write_text(block, encoding="utf-8")
        return WriteOutcome(rel_path, "created")
    original = target.read_text(encoding="utf-8")
    if begin in original and end in original:
        before, _, rest = original.partition(begin)
        _, _, after = rest.partition(end)
        new_text = f"{before.rstrip()}\n\n{block}{after.lstrip()}"
    else:
        suffix = "" if original.endswith("\n") else "\n"
        new_text = f"{original}{suffix}\n{block}"
    target.write_text(new_text, encoding="utf-8")
    return WriteOutcome(rel_path, "patched")


# ---------------------------------------------------------------------------
# Primary-driver selection (EC-003 — polyglot)
# ---------------------------------------------------------------------------


def pick_primary_driver(
    drivers: list[DriverManifest],
    project_root: Path,
) -> DriverManifest | None:
    """Pick the driver matching the most files at the repository root.

    Args:
        drivers: Drivers already filtered to those matching the project root.
        project_root: Repository root used to resolve detect glob patterns.

    Returns:
        The driver matching the highest number of detect files (ties broken by
        the input order — built-ins after custom, alphabetical), or ``None``
        when ``drivers`` is empty.
    """
    if not drivers:
        return None
    if len(drivers) == 1:
        return drivers[0]

    def _score(driver: DriverManifest) -> int:
        total = 0
        for pattern in driver.detect.files:
            total += sum(1 for _ in project_root.glob(pattern))
        return total

    best = drivers[0]
    best_score = _score(best)
    for candidate in drivers[1:]:
        score = _score(candidate)
        if score > best_score:
            best = candidate
            best_score = score
    return best
