"""Generated feature backlinks for global User Journeys v2."""

# @spec FR-007: generated feature backlinks for every covered feature
# — .specs/features/057-cross-feature-user-journeys-v2/spec.md#fr-007

from __future__ import annotations

from pathlib import Path

from .index import build_journey_index
from .models import JourneyIssue, JourneySeverity
from .paths import feature_backlink_path, relative_to_project


def render_feature_backlinks(project_root: Path) -> dict[str, Path]:
    """Write generated `journeys.md` files for every covered feature.

    Args:
        project_root: Project root containing `.specs/`.

    Returns:
        Mapping of feature slug to generated backlink path.
    """
    index = build_journey_index(project_root)
    outputs: dict[str, Path] = {}
    for feature, journey_ids in sorted(index.by_feature.items()):
        path = feature_backlink_path(project_root, feature)
        path.parent.mkdir(parents=True, exist_ok=True)
        text = _render_backlink_text(project_root, feature, sorted(journey_ids))
        path.write_text(text, encoding="utf-8")
        outputs[feature] = path
    return outputs


def verify_feature_backlinks(project_root: Path) -> list[JourneyIssue]:
    """Return backlink drift issues without modifying files."""
    index = build_journey_index(project_root)
    issues: list[JourneyIssue] = []
    for feature, journey_ids in sorted(index.by_feature.items()):
        path = feature_backlink_path(project_root, feature)
        expected = _render_backlink_text(project_root, feature, sorted(journey_ids))
        if not path.exists():
            issues.append(
                JourneyIssue(
                    code="journey_backlink_missing",
                    severity=JourneySeverity.ERROR,
                    message=f"Generated journey backlink is missing for feature {feature}.",
                    path=path,
                )
            )
            continue
        if path.read_text(encoding="utf-8") != expected:
            issues.append(
                JourneyIssue(
                    code="journey_backlink_drift",
                    severity=JourneySeverity.ERROR,
                    message=f"Generated journey backlink is stale for feature {feature}.",
                    path=path,
                )
            )
    return issues


def _render_backlink_text(project_root: Path, feature: str, journey_ids: list[str]) -> str:
    """Render a deterministic generated backlink file."""
    lines = [
        f"# User Journeys for {feature}",
        "",
        "<!-- generated by livespec journey backlinks; do not edit manually -->",
        "",
    ]
    for journey_id in journey_ids:
        source = project_root / ".specs" / "journeys" / journey_id / "journey.yaml"
        lines.append(f"- [{journey_id}]({relative_to_project(project_root, source)})")
    lines.append("")
    return "\n".join(lines)


__all__ = ["render_feature_backlinks", "verify_feature_backlinks"]
